[pytest]
python_files = *test*
markers = 
  positive: Позитивные проверки,
  positive_capitalize :Позитивные capitalize,
  positive_trim: Позитивные trim,
  positive_contains: Позитивные contains,
  positive_delete_symbol: Позитивные delete_symbol,
  negative: Негативные проверки,
  negative_capitalize: Негативные capitalize,
  negative_trim: Негативные trim,
  negative_contains: Негативные contains,
  negative_delete_symbol: Негативные delete_symbol